{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoScaler
metadata:
  annotations:
    {{- include "ui.labels" . | nindent 4 }}
spec:
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: react-ui
  targetCPUUtilizationPercentage: 90
{{- end }}
